apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    app: api
    tier: backend
spec:
  type: LoadBalancer
  selector:
    app: api
    tier: backend
  ports:
    - protocol: TCP
      port: 3333
      targetPort: 3333
      name: http